# Site settings
title: Fonso's web of holding
email: fonsopp@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Este es mi bloc de notas particular. No garantizo
  coherencia, así que lee bajo tu cuenta y riesgo.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://megalomono.github.io" # the base hostname & protocol for your site
github_username:  megalomono

# Build settings
markdown: kramdown
